### ISSUE TITLE
Can you show any use case?

### ISSUE THREAD

**Issue by palvarezcordoba** [evilsocket/ergo-planes-detector#1]
This project is cool.
But I'm questioning myself if there is a real, useful use case.
As a learning project I think this is nice.
But could this be useful?
Maybe to get pictures from google maps and search flying airplanes. But is it useful? XD
Maybe for CIA, CNI or something like but they should already have something like xD
Maybe it could be useful for an airport but only if they have real time (or near) pictures (and I don't know a way of do it)

**Comment by evilsocket** [comment]
maybe it's useful to learn ML? this is a more practical use case https://github.com/evilsocket/ergo-pe-av
